global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'actual-ml-inference'
    static_configs:
      - targets: ['actual-ml-inference:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
