apiVersion: v1
kind: Service
metadata:
  name: actual-sync-service
  namespace: actual-training
spec:
  type: NodePort
  selector:
    app: actual-sync
  ports:
    - name: http
      port: 5006
      targetPort: 5006
      nodePort: 30080
      protocol: TCP
